- name: Finds latest influxevent version
  shell: curl -s https://gitlab.com/api/v4/projects/18707017/releases/ | jq '.[]' | jq -r '.name' | head -1
  register: _latest

- debug:
    var: _latest

- name: Fetches latest version
  get_url:
    url: https://gitlab.com/devopsworks/tools/influxevent/-/releases/{{ _latest.stdout_lines.0 }}/downloads/binaries/influxevent-amd64-{{ _latest.stdout_lines.0 }}.gz
    dest: /tmp/influxevent.gz

- name: Fecth & unarchive influxevent
  # can not use unachive, does not support gz
  shell:
    src: gunzip -cd /tmp/influxevent.gz > /usr/local/bin/influxevent && chmod 755 /usr/local/bin/influxevent
