- name: Finds latest influxevent version
  uri:
    url: https://gitlab.com/api/v4/projects/18707017/releases
    status_code:
      - 200
  register: __influxevent_repo_info

- set_fact:
    __influxevent_latest_version: '{{ __influxevent_repo_info.json.0["name"] }}'

- name: Fetches latest version
  get_url:
    url: https://gitlab.com/devopsworks/tools/influxevent/-/releases/{{ __influxevent_latest_version }}/downloads/binaries/influxevent-amd64-{{ __influxevent_latest_version }}.gz
    dest: /tmp/influxevent.gz

- name: Fetch & unarchive influxevent
  # can not use unachive, does not support gz
  shell: gunzip -cd /tmp/influxevent.gz > /usr/local/bin/influxevent && chmod 755 /usr/local/bin/influxevent
