- name: Checks if influxevent is already present
  stat:
    path: /usr/local/bin/influxevent
  register: __influxevent

- include: influxevent.yml
  when: not __influxevent.stat.exists or influxevent_force_install
  tags:
    - influxevent

