---
- name: Checks if influxevent is already present
  stat:
    path: /usr/local/bin/influxevent
  register: __influxevent
  tags:
    - influxevent

- include_tasks:
    file: influxevent.yml
    apply:
      tags:
        - influxevent
  when: not __influxevent.stat.exists or influxevent_force_install
  tags:
    - always
